import React from 'react';

const TermsOfService = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 text-slate-200">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>

      <h2 className="text-2xl font-semibold mt-8 mb-4">1. Introduction</h2>
      <p>
        Welcome to CreatAI ("Website"). These Terms of Service ("Terms") govern your use of our website and the services we provide, including tools for generating marketing content for social media, startups, and other content marketing purposes ("Services"). By accessing or using our Website and Services, you agree to be bound by these Terms.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">2. Use of Services</h2>
      <h3 className="text-xl font-semibold mt-6 mb-2">2.1 Eligibility</h3>
      <p>
        You must be at least 18 years old to use our Services. By using our Website and Services, you represent and warrant that you meet this eligibility requirement.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">2.2 Account Registration</h3>
      <p>
        To access certain features of our Services, you may be required to create an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your account credentials and for any activities or actions under your account.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">2.3 Acceptable Use</h3>
      <p>
        You agree to use our Services only for lawful purposes and in accordance with these Terms. You agree not to use our Services:
      </p>
      <ul className="list-disc pl-5 mb-4">
        <li>In any way that violates any applicable federal, state, local, or international law or regulation.</li>
        <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way.</li>
        <li>To send, knowingly receive, upload, download, use, or re-use any material that does not comply with these Terms.</li>
        <li>To transmit, or procure the sending of, any advertising or promotional material without our prior written consent.</li>
        <li>To impersonate or attempt to impersonate CreatAI, a CreatAI employee, another user, or any other person or entity.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-4">3. Content and Intellectual Property</h2>
      <h3 className="text-xl font-semibold mt-6 mb-2">3.1 User Content</h3>
      <p>
        You retain all rights to any content you create using our Services ("User Content"). By submitting User Content to our Website, you grant CreatAI a non-exclusive, worldwide, royalty-free, transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the User Content in connection with the Services.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">3.2 AI-Generated Content</h3>
      <p>
        All content generated by our AI tools is intended to be free from copyright issues. However, users are responsible for ensuring that the content generated does not infringe on any existing trademarks or copyrights. If you use AI-generated content that is found to be too similar to trademarked or copyrighted material, CreatAI is not liable for any claims arising from such use. You agree to use AI-generated content at your own risk and acknowledge that CreatAI does not guarantee the originality of AI-generated content.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">3.3 Intellectual Property Rights</h3>
      <p>
        All content, features, and functionality available on our Website and Services are owned by CreatAI, its licensors, or other providers of such material and are protected by intellectual property laws. You may not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Website, except as authorized by these Terms.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">4. Termination</h2>
      <h3 className="text-xl font-semibold mt-6 mb-2">4.1 Termination by You</h3>
      <p>
        You may terminate your account at any time by following the instructions on our Website. Upon termination, you must cease all use of the Services and delete any copies of materials you have obtained through our Services.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">4.2 Termination by CreatAI</h3>
      <p>
        We may terminate or suspend your account and access to our Services at our sole discretion, without prior notice, if you breach these Terms or for any other reason. Upon termination, all provisions of these Terms which by their nature should survive termination shall survive, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">5. Disclaimers and Limitation of Liability</h2>
      <h3 className="text-xl font-semibold mt-6 mb-2">5.1 Disclaimer of Warranties</h3>
      <p>
        Your use of the Website and Services is at your sole risk. The Website and Services are provided on an "as is" and "as available" basis. CreatAI expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">5.2 Limitation of Liability</h3>
      <p>
        In no event shall CreatAI, its directors, employees, or agents be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your use or inability to use the Services; (ii) any unauthorized access to or use of our servers and/or any personal information stored therein; (iii) any interruption or cessation of transmission to or from our Services; (iv) any bugs, viruses, trojan horses, or the like that may be transmitted to or through our Services by any third party; or (v) any errors or omissions in any content or for any loss or damage of any kind incurred as a result of your use of any content posted, emailed, transmitted, or otherwise made available via the Services, whether based on warranty, contract, tort (including negligence), or any other legal theory, and whether or not CreatAI is advised of the possibility of such damages.
      </p>

      {/* <h2 className="text-2xl font-semibold mt-8 mb-4">6. Governing Law</h2>
      <p>
        These Terms shall be governed and construed in accordance with the laws of [Your State/Country], without regard to its conflict of law provisions. Any legal action or proceeding arising under these Terms will be brought exclusively in the federal or state courts located in [Your State/Country], and you hereby consent to the personal jurisdiction and venue therein.
      </p> */}

      <h2 className="text-2xl font-semibold mt-8 mb-4">6. Changes to Terms</h2>
      <p>
        CreatAI reserves the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on the Website. You are advised to review these Terms periodically for any changes. Changes to these Terms are effective when they are posted on this page.
      </p>

      {/* <h2 className="text-2xl font-semibold mt-8 mb-4">7. Contact Us</h2>
      <p>
        If you have any questions about these Terms, please contact us at [Your Contact Information].
      </p> */}
<br></br>
      <p>
        By using our Website and Services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
      </p>
    </div>
  );
};

export default TermsOfService;
